# wasmtime needs a more recent version of glibc than avaiable in bullseye
FROM python:3.13-slim-bookworm

WORKDIR /app
ENV PATH="/app/.venv/bin:$PATH" \
    UV_COMPILE_BYTECODE=1

RUN apt-get update && \
    apt install -y \
    libc6 &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.11.7 /uv /bin/
COPY pyproject.toml uv.lock /app/
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-dev --frozen

COPY --chmod=0755 scripts/ /app/scripts/
COPY bughog /app/bughog/

ENTRYPOINT [ "/app/scripts/boot/worker.sh" ]
