FROM base

ENV MANAGE_CERTS=1 \
    MANAGE_XVFB=1

# `apt update` was already run in the base image
RUN apt install -y curl gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libnspr4 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils libgbm-dev xvfb dbus-x11 libnss3-tools python3-tk gnome-screenshot procps xxd &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Configure xvfb
    cp /app/scripts/daemon/xvfb /etc/init.d/xvfb &&\
    # Initiate PyAutoGUI
    touch /root/.Xauthority && \
    xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)

COPY subject/web_browser/profiles /app/subject/web_browser/profiles

ENTRYPOINT [ "/app/scripts/boot/worker.sh" ]
