FROM python:3.13-slim-trixie

WORKDIR /app
ENV PATH="/app/.venv/bin:$PATH" \
    UV_COMPILE_BYTECODE=1 \
    MANAGE_CERTS=1 \
    MANAGE_XVFB=1

RUN apt-get update && \
    apt install -y curl gnome-screenshot libgstreamer-plugins-bad1.0-0 libxcursor1 libxrandr2 libxi6 libxkbcommon0 libvulkan1 libegl1 python3-tk xvfb xxd &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Initiate PyAutoGUI
    touch /root/.Xauthority && \
    xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)

COPY --chmod=0755 scripts/ /app/scripts/
RUN cp /app/scripts/daemon/xvfb /etc/init.d/xvfb

COPY pyproject.toml uv.lock /app/
COPY --from=ghcr.io/astral-sh/uv:0.11.7 /uv /bin/
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-dev --frozen

COPY bughog /app/bughog/

ENTRYPOINT [ "/app/scripts/boot/worker.sh" ]
