name: Trigger GitLab build job
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
env:
  GITLAB_PIPELINE_TRIGGER_TOKEN: ${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }}
jobs:

  trigger_build_job:
    runs-on: ubuntu-latest
    steps:
      - name: send triggering request
        run: |
          curl -X POST \
            --fail \
            -F token=$GITLAB_PIPELINE_TRIGGER_TOKEN \
            -F "ref=main" \
            -F "variables[RELEASE_VERSION]=${{github.ref_name}}" \
            https://gitlab.kuleuven.be/api/v4/projects/17581/trigger/pipeline

  package_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
